import { Inter } from "next/font/google";
import "./globals.css";
import Header from './Header'
import Footer from './Footer';
import { Montserrat } from "next/font/google";
import Jumbotron from "./jumbotron";

const montserrat = Montserrat(
  { subsets: ["latin"],
    fallback: ["system-ui" , "arial"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>

        {/* Header component is Here */}
      
        <Header/>
        <Jumbotron/>
                
        {children}

        {/* Footer component Is Here */}

        <Footer/>

      </body>
    </html>
  );
}
